namespace: garuda
name: ipt-server
images:
  iptServer: "ghcr.io/garuda-tunnel/garuda-ipt-server@sha256:3fc1a5c8501571cd3380df616db40d8b1307c9af2e3475b106320bb091705b4c"
  powerdns: "ghcr.io/garuda-tunnel/garuda-powerdns@sha256:b92e56901599c47aa6d7fe6de0fba4f8e82823b00b6aa2819d84498977caaca6"
  frr: ""
routes: []
pbrInterfaces:
  - backbone
nicAttach:
  - backbone
cleanConntrack: false
domainRouteTtl: 300
pinningEgress: {}
pinningTtl: 86400
pinningApiPort: 80
labels: {}
# ospf is null when omitted; FRR sidecar is then NOT rendered.
ospf: null
